In [25]:
import pandas as pd
import numpy as np
import matplotlib.pyplot as plt
import seaborn as sb

In [12]:
df = pd.read_clipboard(index_col=False)

In [13]:
df

index  a  b  c
0      1  2  3  4
1      2  3  4  5

In [23]:
df1 = df.iloc[:, 0:-3]
df1

index
0      1
1      2

In [27]:
print(sb.get_dataset_names())

['anagrams', 'anscombe', 'attention', 'brain_networks', 'car_crashes', 'diamonds', 'dots', 'exercise', 'flights', 'fmri', 'gammas', 'geyser', 'iris', 'mpg', 'penguins', 'planets', 'taxis', 'tips', 'titanic']


In [28]:
df = sb.load_dataset('attention')
df.head()

Unnamed: 0  subject attention  solutions  score
0           0        1   divided          1    2.0
1           1        2   divided          1    3.0
2           2        3   divided          1    3.0
3           3        4   divided          1    5.0
4           4        5   divided          1    4.0

In [29]:
df.shape

(60, 5)

In [30]:
df.info()

<class 'pandas.core.frame.DataFrame'>
RangeIndex: 60 entries, 0 to 59
Data columns (total 5 columns):
 #   Column      Non-Null Count  Dtype  
---  ------      --------------  -----  
 0   Unnamed: 0  60 non-null     int64  
 1   subject     60 non-null     int64  
 2   attention   60 non-null     object 
 3   solutions   60 non-null     int64  
 4   score       60 non-null     float64
dtypes: float64(1), int64(3), object(1)
memory usage: 2.5+ KB


In [31]:
df.columns.tolist()

['Unnamed: 0', 'subject', 'attention', 'solutions', 'score']

In [40]:
def multi_frequency(ds,vars):
    frequency=ds[vars].isnull().sum()
    percentage=ds[vars].isnull().sum()/len(vars)*100
    df=pd.concat([frequency,percentage], axis=1, keys=['num_rows_missing', 'pct_rows_missing'])
    return df
multi_frequency(df, ['solutions', 'attention'])

num_rows_missing  pct_rows_missing
solutions                 0               0.0
attention                 0               0.0

In [47]:
def multi_frequency(ds,vars):
    
    frequency=ds[vars].isna().sum()
    percentage=ds[vars].isna().sum()/len(ds)
    df=pd.concat([frequency,percentage], axis=1, keys=['num_rows_missing', 'pct_rows_missing'])
    return df
multi_frequency(df, ['solutions', 'attention'])

num_rows_missing  pct_rows_missing
solutions                 0               0.0
attention                 0               0.0

In [49]:
# # ⚠️Function for renaming duplicate columns

# cols=pd.Series(houses.columns)
# for dup in houses.columns[houses.columns.duplicated(keep=False)]: 
#     cols[houses.columns.get_loc(dup)] = ([dup + '_' + str(d_idx) 
#                                      if d_idx != 0 
#                                      else dup 
#                                      for d_idx in range(houses.columns.get_loc(dup).sum())]
#                                     )
# houses.columns=cols

In [ ]:
def nulls_by_rows(df):
    return pd.concat([
        df.isna().sum(axis=l).rename('n_missing'),
        df.isna().mean(axis=1).rename('percent_missing')
    ], axis=1).value counts().sort_index()


In [ ]:
# From Clustering Prepare exercises ⚠️

print('Before dropping nulls, %d rows, %d cols' % df.shape)
df = wrangle_zillow.handle_missing_values(df, prop_required_column=.5, prop_required_row=.5)
print('After dropping nulls, %d rows, %d cols' % df.shape)

In [51]:
arr2= np.array([[4, 2, 3, 2, 1, 8],
                [5, 4, 6, 7, 8, 9]])
np.shape(arr2)

(2, 6)

In [53]:
arr2.shape[1]

6

In [58]:
x = np.arange(36).reshape(-3, 9)
x

array([[ 0,  1,  2,  3,  4,  5,  6,  7,  8],
       [ 9, 10, 11, 12, 13, 14, 15, 16, 17],
       [18, 19, 20, 21, 22, 23, 24, 25, 26],
       [27, 28, 29, 30, 31, 32, 33, 34, 35]])

In [63]:
x = np.arange(36).reshape(-3, 9)
x

array([[ 0,  1,  2,  3,  4,  5,  6,  7,  8],
       [ 9, 10, 11, 12, 13, 14, 15, 16, 17],
       [18, 19, 20, 21, 22, 23, 24, 25, 26],
       [27, 28, 29, 30, 31, 32, 33, 34, 35]])

In [79]:
x = np.arange(54).reshape(-6, 9)
x

array([[ 0,  1,  2,  3,  4,  5,  6,  7,  8],
       [ 9, 10, 11, 12, 13, 14, 15, 16, 17],
       [18, 19, 20, 21, 22, 23, 24, 25, 26],
       [27, 28, 29, 30, 31, 32, 33, 34, 35],
       [36, 37, 38, 39, 40, 41, 42, 43, 44],
       [45, 46, 47, 48, 49, 50, 51, 52, 53]])